apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: tk-doc-dev
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: dev
  secretRef:
    name: tk-doc
  url: https://github.com/dedkola/tk-doc.git
